### ISSUE TITLE
Get Axis camera rtsp stream uri failed

### ISSUE THREAD

**Issue by onionf91** [milg0/onvif-java-lib#6]
I try to get AXIS M3006 Network Camera RTSP uri through onvif, but failed with error message "Unhandled exception: InputStream does not represent a valid SOAP 1.2 Message".

There is my code

```
OnvifDevice onvifDevice = new OnvifDevice(cameraAddress, username, password);
onvifDevice.getSoap().setLogging(true);
String profileToken = onvifDevice.getDevices().getProfiles().get(0).getToken();
String url = onvifDevice.getMedia().getRTSPStreamUri(profileToken);
```

and SOAP response from log is

```
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope
        xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:c14n="http://www.w3.org/2001/10/xml-exc-c14n#"
        xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
        xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
        xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"
        xmlns:wsa5="http://www.w3.org/2005/08/addressing"
        xmlns:xmime="http://tempuri.org/xmime.xsd"
        xmlns:xop="http://www.w3.org/2004/08/xop/include"
        xmlns:wsrfbf="http://docs.oasis-open.org/wsrf/bf-2"
        xmlns:wstop="http://docs.oasis-open.org/wsn/t-1"
        xmlns:tt="http://www.onvif.org/ver10/schema"
        xmlns:acert="http://www.axis.com/vapix/ws/cert"
        xmlns:wsrfr="http://docs.oasis-open.org/wsrf/r-2"
        xmlns:aa="http://www.axis.com/vapix/ws/action1"
        xmlns:acertificates="http://www.axis.com/vapix/ws/certificates"
        xmlns:aentry="http://www.axis.com/vapix/ws/entry"
        xmlns:aev="http://www.axis.com/vapix/ws/event1"
        xmlns:aeva="http://www.axis.com/vapix/ws/embeddedvideoanalytics1"
        xmlns:ali1="http://www.axis.com/vapix/ws/light/CommonBinding"
        xmlns:ali2="http://www.axis.com/vapix/ws/light/IntensityBinding"
        xmlns:ali3="http://www.axis.com/vapix/ws/light/AngleOfIlluminationBinding"
        xmlns:ali4="http://www.axis.com/vapix/ws/light/DayNightSynchronizeBinding"
        xmlns:ali="http://www.axis.com/vapix/ws/light"
        xmlns:apc="http://www.axis.com/vapix/ws/panopsiscalibration1"
        xmlns:arth="http://www.axis.com/vapix/ws/recordedtour1"
        xmlns:ascm="http://www.axis.com/vapix/ws/siblingcameramonitor1"
        xmlns:asd="http://www.axis.com/vapix/ws/shockdetection"
        xmlns:aweb="http://www.axis.com/vapix/ws/webserver"
        xmlns:tan1="http://www.onvif.org/ver20/analytics/wsdl/RuleEngineBinding"
        xmlns:tan2="http://www.onvif.org/ver20/analytics/wsdl/AnalyticsEngineBinding"
        xmlns:tan="http://www.onvif.org/ver20/analytics/wsdl"
        xmlns:tds="http://www.onvif.org/ver10/device/wsdl"
        xmlns:tev1="http://www.onvif.org/ver10/events/wsdl/NotificationProducerBinding"
        xmlns:tev2="http://www.onvif.org/ver10/events/wsdl/EventBinding"
        xmlns:tev3="http://www.onvif.org/ver10/events/wsdl/SubscriptionManagerBinding"
        xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2"
        xmlns:tev4="http://www.onvif.org/ver10/events/wsdl/PullPointSubscriptionBinding"
        xmlns:tev="http://www.onvif.org/ver10/events/wsdl"
        xmlns:timg="http://www.onvif.org/ver20/imaging/wsdl"
        xmlns:tptz="http://www.onvif.org/ver20/ptz/wsdl"
        xmlns:trt="http://www.onvif.org/ver10/media/wsdl"
        xmlns:ter="http://www.onvif.org/ver10/error"
        xmlns:tns1="http://www.onvif.org/ver10/topics"
        xmlns:tnsaxis="http://www.axis.com/2009/event/topics">
    <SOAP-ENV:Header></SOAP-ENV:Header>
    <SOAP-ENV:Body>
        <trt:GetStreamUriResponse>
            <trt:MediaUri>
                <tt:Uri>
                    rtsp://192.168.1.90/onvif-media/media.amp?profile=profile_1_h264&amp;sessiontimeout=60&amp;streamtype=unicast
                </tt:Uri>
                <tt:InvalidAfterConnect>false</tt:InvalidAfterConnect>
                <tt:InvalidAfterReboot>false</tt:InvalidAfterReboot>
                <tt:Timeout>PT0S</tt:Timeout>
            </trt:MediaUri>
        </trt:GetStreamUriResponse>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

According to envelop namespace uri

```
xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
```

This response is SOAP 1.1, but SAAJ expect response as SOAP 1.2. The SOAPPart1_2Impl.java class throw exception when soapResponse(SOAPMessage) call getBody function. After catch SOAPException, getStreamUri function receive null response and return uri string as null.

```
Unmarshaller unmarshaller = JAXBContext.newInstance(soapResponseElem.getClass()).createUnmarshaller();
try {
    soapResponseElem = unmarshaller.unmarshal(soapResponse.getSOAPBody().extractContentAsDocument());
}
...
catch (SOAPException e) {
  onvifDevice.getLogger().error("Unhandled exception: "+e.getMessage());
  e.printStackTrace();
  return null;
}
```

**Comment by onionf91** [comment]
In the com.sun.xml.internal.messaging.saaj.soap package has also ver1_1.SOAPPart1_1Imp class, but soap parser always tries soap 1.2? So this is a SAAJ's bug? or have you any idea how to solve this problem?

**Comment by davidjytang** [comment]
I am seeing this issue as well. @milg0 would you need a demo link to the camera? I will gladly dig out the camera and set it up for you to connect.

**Comment by milg0** [comment]
I'm going to look for this issue tomorrow and next week.
@juiyout That would be a great help to me.

**Comment by onionf91** [comment]
Hello @milg0 , this is the camera demo link

```
http://root:root@210.61.67.37:1090
rtsp://root:root@210.61.67.37:10090
```

Hope this helps

**Comment by milg0** [comment]
Please use the new release onvif-2016-02-05.jar and let me know if you still have the same error (there might be a logging error, but the result should be okay).

**Comment by davidjytang** [comment]
OMG, @milg0 so cool. I'm in a region where people celebrate holidays these days. Let me test this before end of this week.

**Comment by onionf91** [comment]
It's working now. Thanks @milg0 .

**Comment by alpeshprajapati89** [comment]
OnvifDevice onvifDevice = new OnvifDevice(cameraAddress, username, password);

how to add SOAPException in android studio.
I use external jar javax.xml.soap.jar for this but android studio fail to build.
Please help for this.

**Comment by alpeshprajapati89** [comment]
Error:trouble processing "javax/xml/soap/SOAPException.class":
Error:Ill-advised or mistaken usage of a core class (java.* or javax.*)
Error:when not building a core library.
Error:This is often due to inadvertently including a core library file
Error:in your application's project, when using an IDE (such as
Error:Eclipse). If you are sure you're not intentionally defining a
Error:core class, then this is the most likely explanation of what's
Error:going on.
Error:However, you might actually be trying to define a class in a core
Error:namespace, the source of which you may have taken, for example,
Error:from a non-Android virtual machine project. This will most
Error:assuredly not work. At a minimum, it jeopardizes the
Error:compatibility of your app with future versions of the platform.
Error:It is also often of questionable legality.
Error:If you really intend to build a core library -- which is only
Error:appropriate as part of creating a full virtual machine
Error:distribution, as opposed to compiling an application -- then use
Error:the "--core-library" option to suppress this error message.
Error:If you go ahead and use "--core-library" but are in fact
Error:building an application, then be forewarned that your application
Error:will still fail to build or run, at some point. Please be
Error:prepared for angry customers who find, for example, that your
Error:application ceases to function once they upgrade their operating
Error:system. You will be to blame for this problem.
Error:If you are legitimately using some code that happens to be in a
Error:core package, then the easiest safe alternative you have is to
Error:repackage that code. That is, move the classes in question into
Error:your own package namespace. This means that they will never be in
Error:conflict with core system classes. JarJar is a tool that may help
Error:you in this endeavor. If you find that you cannot do this, then
Error:that is an indication that the path you are on will ultimately
Error:lead to pain, suffering, grief, and lamentation.
